AnimalShelter/Models/Animal.cs
using System.ComponentModel.DataAnnotations;
using System;

namespace AnimalShelter.Models
{
  public class Animal
  {
    [RequiredAttribute]
    public int AnimalId { get; set; }
    public string Description { get; set; }
    public string Name { get; set; }
    public DateTime ArrivalDate { get; set; }
  }
}

AnimalShelter/Models/AnimalShelterContext.cs
using Microsoft.EntityFrameworkCore;

namespace AnimalShelter.Models
{
  public class AnimalShelterContext : DbContext
  {
    public DbSet<Animal> Animals { get; set; }

    public AnimalShelterContext(DbContextOptions options) : base(options) { }
  }
}                                                                                     

AnimalShelter/Models/Animals.cs
namespace AnimalShelter.Models
{
  public class Animal
  {
    public int AnimalId { get; set; }
    public string Description { get; set; }
    public string Name { get; set; }
    public string Arrival { get; set; } 

  }
}

AnimalShelter/Controllers/AnimalController.cs
using Microsoft.AspNetCore.Mvc;
using AnimalShelter.Models;
using System.Collections.Generic;
using System.Linq;

namespace AnimalShelter.Controllers
{
  public class AnimalsController : Controller
  {
    private readonly AnimalShelterContext _db;

    public AnimalsController(AnimalShelterContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Animal> model = _db.Animals.OrderBy(animal => animal.Name).ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Animal animal)
    {
      _db.Animals.Add(animal);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      Animal thisAnimal = _db.Animals.FirstOrDefault(animal => animal.AnimalId == id);
      return View(thisAnimal);
    }
    public ActionResult Delete(int id)
    {
      Animal thisAnimal = _db.Animals.FirstOrDefault(animal => animal.AnimalId == id);
      return View(thisAnimal);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Animal thisAnimal = _db.Animals.FirstOrDefault(animal => animal.AnimalId == id);
      _db.Animals.Remove(thisAnimal);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

AnimalShelter/Controllers/AnimalsController.cs
using Microsoft.AspNetCore.Mvc;
using AnimalShelter.Models;
using System.Collections.Generic;
using System.Linq;

namespace AnimalShelter.Controllers
{
  public class AnimalsController : Controller
  {
    private readonly AnimalShelterContext _db;

    public AnimalsController(AnimalShelterContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Animal> model = _db.Animals.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Animal animal)
    {
      _db.Animals.Add(animal);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      Animal thisAnimal = _db.Animals.FirstOrDefault(animal => animal.AnimalId == id);
      return View(thisAnimal);
    }

  }
}

AnimalShelter/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace AnimalShelter.Controllers
{
    public class HomeController : Controller
    {

      [HttpGet("/")]
      public ActionResult Index()
      {
        return View();
      }

    }
}

AnimalShelter/Views/Animals/Create.cshtml
@{
  Layout = "_Layout";
}

@model AnimalShelter.Models.Animal

<h4>Add a new animal</h4>

@using (Html.BeginForm())
{
  <br>
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name, new { @class = "form-control", placeholder = "Animal Name", required="required"})
  <br>
  @Html.LabelFor(model => model.Description, "Breed")
  @Html.TextBoxFor(model => model.Description, new { @class = "form-control", placeholder = "Type", required="required"})
  <br>
  @Html.LabelFor(model => model.ArrivalDate, "Arrival Date")
  // No need for the {yyyy-MM-dd} format or the @ in front of the type="date"
  @Html.TextBoxFor(model => model.ArrivalDate, new { @class = "form-control", type = "date" })
  <br>
  <input type="submit" value="Add new animal" />
}
<br>
<p>@Html.ActionLink("Show all animals", "Index")</p>

AnimalShelter/Views/Animals/Delete.cshtml
@{
  Layout = "_Layout";
}

@model AnimalShelter.Models.Animal

<h2>Are you sure you want to delete this?</h2>

@Html.DisplayNameFor(model => model.Description): @Html.DisplayFor(model => model.Description)
@using (Html.BeginForm())
{
    <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to Animals", "Index")

AnimalShelter/Views/Animals/Details.cshtml
@{
  Layout = "_Layout";
}

@model AnimalShelter.Models.Animal

<h2>Animal Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.Description): @Html.DisplayFor(model => model.Description)</h3>
<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h3>
<h3>@Html.DisplayNameFor(model => model.ArrivalDate): @Html.DisplayFor(model => model.ArrivalDate)</h3>
<p>@Html.ActionLink("Back to list", "Index")</p>

<p>@Html.ActionLink("Delete Item", "Delete", new { id = Model.AnimalId })</p>

AnimalShelter/Views/Animals/Index.cshtml
@{
  Layout = "_Layout";
}

@using AnimalShelter.Models;

<h2>Animals</h2>

@if(@Model.Count == 0)
{
  <h4>There are no animals at this time!</h4>
  <h4>@Html.ActionLink("Add new animal", "Create")</h4>
}

<ul>
  @foreach (Animal animal in Model)
  {
    <p>@Html.ActionLink($"{animal.Name}", "Details", new {id = animal.AnimalId})</p>
  }
</ul>

    <h4>@Html.ActionLink("Add new animal", "Create")</h4>

AnimalShelter/Views/Home/Index.cshtml
@{
  Layout = "_Layout";
}

<h1>Welcome to the The Animal Shelter!</h1>
<p>@Html.ActionLink("See all animals", "Index", "Animals")</p> 

AnimalShelter/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Animal Shelter</title>
    <link 
    href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" 
    rel="stylesheet" 
    integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" 
    crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="~/css/styles.css">
  </head>
  <body>
    @RenderBody()
  </body>
</html>